---
title: "OTC_synthesis_results"
author: "Courtney Collins"
output: html_document
---
#load libraries 
```{r setup, echo=FALSE, warning=FALSE, error=FALSE, message=F}
library(tidybayes)
library(magrittr)
library(dplyr)
library(purrr)
library(forcats)
library(tidyr)
library(modelr)
library(tidybayes)
library(ggplot2)
library(ggstance)
library(cowplot)
library(rstan)
library(brms)
library(ggrepel)
library(RColorBrewer)
library(gganimate)
library(bayestestR)
library(here)
library(ggridges)
#library(ggdistribute)
library(knitr)
library(gridExtra)
library(brms)


rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

```


```{r load models,echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#takes a minute--update to full local path of model outputs 
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_flow.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_flowend.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_green.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_disp.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_fruit.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m2x_sen.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m5x_flow.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m6x_disp.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m7x_disp.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m8x_green.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fit_m8x_sen.Rdata")

#load back-scaling constants for each phenophase 
load("~/Git/OTC_synthesis_analyses/Data/brms_output/greenscale.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/senscale.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/flowscale.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/flowendscale.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/fruitscale.Rdata")
load("~/Git/OTC_synthesis_analyses/Data/brms_output/dispscale.Rdata")
scales<-rbind(flowscales, flowendscales, fruitscales, dispscales, senscales, greenscales)
```




###Main OTC effects 

```{r main OTC effects,  echo=FALSE, warning=FALSE, error=FALSE, message=F}
#pull out m2x posteriors for main OTC effect
postflow2<- as_tibble(fixef(fit_m2x_flow, summary=F))%>%dplyr::select(-Intercept)
postflowend2<- as_tibble(fixef(fit_m2x_flowend, summary=F))%>%dplyr::select(-Intercept)
postfruit2<- as_tibble(fixef(fit_m2x_fruit, summary=F))%>%dplyr::select(-Intercept)
postdisp2<- as_tibble(fixef(fit_m2x_disp,summary=F))%>%dplyr::select(-Intercept)
postgreen2<- as_tibble(fixef(fit_m2x_green, summary=F))%>%dplyr::select(-Intercept)
postsen2<- as_tibble(fixef(fit_m2x_sen, summary=F))%>%dplyr::select(-Intercept)

flow_eti <- ci(postflow2, method = "ETI", ci= c(0.9, 0.95))%>%mutate(phen='Flower')
flowend_eti <- ci(postflowend2, method = "ETI", ci =c(0.9, 0.95))%>%mutate(phen='Flowerend')
fruit_eti <- ci(postfruit2, method = "ETI", ci =c(0.9, 0.95))%>%mutate(phen='Fruit')
disp_eti <- ci(postdisp2, method = "ETI", ci =c(0.9, 0.95))%>%mutate(phen='Disp')
green_eti <- ci(postgreen2, method = "ETI", ci = c(0.9, 0.95))%>%mutate(phen='Green')
sen_eti <- ci(postsen2, method = "ETI", ci = c(0.9, 0.95))%>%mutate(phen='Sen')
eti<-rbind(flow_eti, flowend_eti, fruit_eti, disp_eti, green_eti, sen_eti)
etiw<-pivot_wider(eti, names_from = "CI", values_from = c("CI_low", "CI_high"))

```


```{r posteriors,  echo=FALSE,  warning=FALSE, error=FALSE, message=F}
postflow2<- as_tibble(fixef(fit_m2x_flow, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Flower", scale=flowscales$sd, order=5)
postflowend2<- as_tibble(fixef(fit_m2x_flowend, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Flowerend", scale=flowendscales$sd, order=4)
postfruit2<- as_tibble(fixef(fit_m2x_fruit, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Fruit", scale=fruitscales$sd, order=3)
postdisp2<- as_tibble(fixef(fit_m2x_disp, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Disp",scale=dispscales[1,2], order=2)
postgreen2<- as_tibble(fixef(fit_m2x_green, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Green", scale=greenscales[1,2], order=6)
postsen2<- as_tibble(fixef(fit_m2x_sen, summary=F))%>%dplyr::select(-Intercept)%>%mutate(phen="Sen", scale=senscales$sd, order=1)

post2<-as_tibble(rbind(postflow2, postflowend2, postfruit2, postgreen2, postdisp2, postsen2))
  
post2<-group_by(post2,phen) %>%
  mutate(Estimate = mean(treatmentOTC), Err = sd(treatmentOTC))%>%
  ungroup()

#unscale estimates and CIs for Table 3
scales<-select(post2, phen, scale, Estimate, Err)%>%distinct(.)
etiw<-left_join(etiw, scales)
etiw$Estimate<-etiw$Estimate*etiw$scale
etiw$Err<-etiw$Err*etiw$scale
etiw$CI_low_90<-etiw$CI_low_90*etiw$scale
etiw$CI_low_95<-etiw$CI_low_95*etiw$scale
etiw$CI_high_90<-etiw$CI_high_90*etiw$scale
etiw$CI_high_95<-etiw$CI_high_95*etiw$scale
etiw<-dplyr::select(etiw, Parameter, phen, Estimate, Err, CI_low_90, CI_high_90, CI_low_95, CI_high_95)

```

*Fig 3*  
* Model 2x posteriors with bayestest eti intervals 

```{r plot main effects,  echo=FALSE,  warning=FALSE, error=FALSE, message=F}

#make with facet wraps 
post2$facet = factor(post2$phen, levels = c("Green",  "Sen", "Flower", "Flowerend", "Fruit", "Disp"))
names <- c(
  `Green` = "Greenup",
  `Flower` = "Flowering",
  `Flowerend` = "End of Flowering",
  `Fruit` = "Fruiting", 
  `Disp` = "Dispersal", 
  `Sen`="Senescence")

post2<-left_join(post2, eti)
post3<-pivot_wider(post2, names_from = "CI", values_from = c("CI_low", "CI_high"))

plot<-ggplot(post3, aes(x = treatmentOTC*scale, fill= facet)) + 
geom_vline(data = plyr::ddply(post3, "facet"), aes(xintercept=CI_low_90*scale),color="red",lty=2,size=1)+
geom_vline(data = plyr::ddply(post3, "facet"), aes(xintercept=CI_high_90*scale), color="red",lty=2,size=1)+
geom_vline(data = plyr::ddply(post3, "facet"), aes(xintercept=CI_low_95*scale),color="grey",lty=2,size=1)+
geom_vline(data = plyr::ddply(post3, "facet"), aes(xintercept=CI_high_95*scale),color="grey",lty=2,size=1)+
      facet_wrap(~facet,ncol=1, strip.position="right")+
 theme_classic()+   xlim(-6,4)+
  geom_density()+ 
  scale_y_continuous(limits = c(0,1.5))+
  theme(legend.position="none")+
    scale_fill_manual(values=c( "#52854C", "#D05A45", "#FAEFD1", "#F3DF6C", "#E069C6", "#9A7B4F"))+
  #d99694-salmon red 
 geom_vline(xintercept = 0, color='black')+
xlab(expression(Delta*"Days (OTC - CTL)")) + ylab("Density") 

plot
```


###Interactions

*Fig 4*

*Interactions OTC by soil moisture for flowering and OTC by winter removal for dispersal  

```{r plot interactions categorical, echo=FALSE, warning=FALSE, error=FALSE, message=F, results=FALSE, fig.width=10, fig.height=8}
#set custom plotting theme-grobs on y axis  
transparent_theme <- theme( axis.title.y = element_blank(), axis.title.x = element_blank(),
                            #axis.text.x = element_blank(), 
                            axis.text.y = element_blank(), 
                            #axis.ticks.x = element_blank(), 
                            axis.ticks.y = element_blank(), 
                            panel.grid = element_blank(), 
                            axis.line = element_blank(), 
                            panel.background = element_blank(), 
                            plot.background = element_blank(), 
                            panel.border = element_blank(), 
                            panel.grid.major = element_blank(), 
                            panel.grid.minor = element_blank(), 
                            panel.grid.major.x = element_blank(),
                            panel.grid.major.y = element_blank())


###Calculate OTC-CTL differences for all model replicates  
dat<-as_tibble(fit_m5x_flow$data)
xx<-unite(dat, all,spp, site_name, subsite, year, remove=F)%>%dplyr::select(site_name,spp, subsite, year, all, treatment, estimate)%>%group_by(all)%>%
  pivot_wider(names_from = treatment, values_from=estimate)%>%
  mutate(diff=(OTC-CTL))%>%filter(!is.na(diff))

#join with soil moisture info 
subsites<-read.csv("~/Git/OTC_synthesis_analyses/Data/LOOKUPS/subsites.csv") 
moist<-filter(subsites,subsite %in% dat$subsite)%>%group_by( subsite)%>%dplyr::select(subsite, commtype)%>%distinct(.)
#reorder groups and shorten subsite names for plotting 
xxx<-left_join(xx, moist)%>%mutate(order=case_when(commtype=="DRY"~1,
                                                   commtype=="MOIST"~3,
                                                commtype=="WET"~2))%>%
  separate(subsite, c("site_name", 'sub_name', 'inits', 'xtra',remove=F))%>% 
  unite(sub, site_name, sub_name)%>%  
  mutate(xtra=ifelse(is.na(xtra),xtra,inits))%>%unite(sub_name, sub, xtra, na.rm=T)%>%mutate(sub_name=tolower(sub_name))
  

#ggplot of replicate OTC-CTL differences by subsite and soil moisture 
C<-ggplot(data=xxx, aes(x = reorder(sub_name,order), y=(diff*15.82), fill=commtype)) + geom_boxplot()+theme_classic()+
   ylab(expression(Delta*"Days (OTC - CTL)"))+ scale_fill_brewer("Blues")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=8))+
  geom_hline(yintercept = 0, color='grey', lty=2)+ xlab(' ') + ylim(-20,20)+
  labs(fill="Soil moisture")

###Calculate pairwise differences between moisture types from model posteriors
postm5xflow<- as_tibble(posterior_samples(fit_m5x_flow, pars = 
c("b_treatmentOTC","b_treatmentOTC:commtypeMOIST", "b_treatmentOTC:commtypeWET")))
postm5xflow$DRY<-postm5xflow$b_treatmentOTC
postm5xflow$MOIST<-postm5xflow$`b_treatmentOTC:commtypeMOIST`+postm5xflow$DRY 
postm5xflow$WET<-postm5xflow$`b_treatmentOTC:commtypeWET`+postm5xflow$DRY 

postm5xflow<-dplyr::select(postm5xflow, DRY, MOIST, WET)%>%
  pivot_longer(cols=c(DRY, MOIST, WET), names_to = "commtype", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
xdensity <- ggplot(postm5xflow, aes(x=value*flowscales$sd)) + geom_density(aes(fill=commtype), alpha=0.8) +
   scale_fill_brewer("Blues")+ transparent_theme+
  ggtitle(expression(Delta*"Days (OTC - CTL) Flowering"))+
theme(legend.position = "none", 
      plot.title = element_text(size = 10, hjust = 1, vjust=1.5))

# Create the external graphical elements called a 'grop' in Grid terminology
p2_grob = ggplotGrob(xdensity)

# Insert p2_grob inside the ggplot
c<-C + annotation_custom(grob = p2_grob, ymin = 12, ymax = 22)

#dispersal x otc removal----
###Calculate OTC-CTL differences for all model replicates 
dat<-as_tibble(fit_m6x_disp$data)
xx<-unite(dat, all,spp, site_name, subsite, year, remove=F)%>%dplyr::select(site_name,spp, subsite, year, all, treatment, estimate)%>%group_by(all)%>%
  pivot_wider(names_from = treatment, values_from=estimate)%>%
  mutate(diff=(OTC-CTL))%>%filter(!is.na(diff))

#join with OTC removal info 
rem<-filter(subsites, site_name %in% dat$site_name & OTCWinterRemoval!="")%>%
  group_by(site_name)%>%dplyr::select(site_name, OTCWinterRemoval)%>%distinct(.)

#reorder groups and shorten subsite names for plotting 
xxx<-left_join(xx, rem)%>%mutate(order=case_when(OTCWinterRemoval=="Y"~2,
                             OTCWinterRemoval=="N"~1))%>%
  separate(subsite, c("site_name", 'sub_name', 'inits', 'xtra',remove=F))%>% 
  unite(sub, site_name, sub_name)%>% 
  mutate(xtra=ifelse(is.na(xtra),xtra,inits))%>%unite(sub_name, sub, xtra, na.rm=T)%>%mutate(sub_name=tolower(sub_name))
  

#ggplot of replicate OTC-CTL differences by subsite and winter removal 
D<-ggplot(data=xxx, aes(x = reorder(sub_name,order), y=(diff*dispscales[1,2]), fill=OTCWinterRemoval, order=order)) + geom_boxplot()+theme_classic()+
  scale_fill_manual(values=c("#899DA4", "#FAEFD1"))+
  ylab(expression(Delta*"Days (OTC - CTL)"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1 ,size=8))+
  geom_hline(yintercept = 0, color='grey', lty=2)+ xlab(' ')+ ylim(-20,20)
  
###Calculate pairwise differences between moisture types from model posteriors  
postm6xdisp<- as_tibble(posterior_samples(fit_m6x_disp, pars = 
  c("b_treatmentOTC","b_treatmentOTC:OTC_WinterRemovalY")))

postm6xdisp$N<-postm6xdisp$b_treatmentOTC
postm6xdisp$Y<-postm6xdisp$`b_treatmentOTC:OTCWinterRemovalY`+postm6xdisp$N

postm6xdisp<-dplyr::select(postm6xdisp, N,Y)%>%
  pivot_longer(cols=c(N,Y), names_to = "OTC_WinterRemoval", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
xdensity <- ggplot(postm6xdisp, aes(x=value*dispscales[1,2])) + geom_density(aes(fill=OTC_WinterRemoval), alpha=0.8) +
  theme_classic()+ 
  transparent_theme+
  scale_fill_manual(values=c("#899DA4", "#FAEFD1"))+
  ggtitle(expression(Delta*"Days (OTC - CTL) Dispersal"))+
  theme(legend.position = "none", 
        plot.title = element_text(size = 10, hjust = 1, vjust=1.5))

# Create the external graphical elements called a 'grop' in Grid terminology
p2_grob = ggplotGrob(xdensity)

# Insert p2_grob inside the ggplot
d<-  D + annotation_custom(grob = p2_grob, ymin = 12, ymax = 22)

#combine plots c and d 
gridExtra::grid.arrange(c, d, ncol=2)


```


```{r Calculate phenoperiod lengths, echo=FALSE,warning=FALSE, results=F,error=FALSE, message=F}
#calculate length (days) difference between greenup and senescence, flowering and end of flowering, end of flowering and seed dispersal 
postgreensen<-as.data.frame(postsen2$treatmentOTC*senscales$sd)-(postgreen2$treatmentOTC*greenscales[1,2])
postflowflowend<-as.data.frame(postflowend2$treatmentOTC*flowendscales$sd)-(postflow2$treatmentOTC*flowscales$sd)
postflowenddisp<-(postdisp2$treatmentOTC*dispscales[1,2])-as.data.frame(postflowend2$treatmentOTC*flowendscales$sd)

#estimate growing season length (days) between greenup and senescence  
postm2xgreen<- as_tibble(posterior_samples(fit_m2x_green, pars = 
                                             c("b_Intercept")))
postm2xsen<- as_tibble(posterior_samples(fit_m2x_sen, pars = 
                                             c("b_Intercept")))

postgsl<-as.data.frame((postm2xsen$b_Intercept*senscales$sd)+senscales$mean)-
  ((postm2xgreen$b_Intercept*greenscales$sd)+greenscales$mean)
postgsl<-rename(postgsl, length=`(postm2xsen$b_Intercept * senscales$sd) + senscales$mean`)  
mean(postgsl$length)#50.77 days
postgreensen$diff<-postgreensen$`postsen2$treatmentOTC * senscales$sd`
postgreensen$`postsen2$treatmentOTC * senscales$sd`<-NULL

mean(postgreensen$diff)
sd(postgreensen$diff)
mean(postgreensen$diff)/mean(postgsl$length)#percent of total growing season change 


#calculate Intercept vals for Table 3
mean((postm2xsen$b_Intercept*senscales$sd)+senscales$mean)
sd((postm2xsen$b_Intercept*senscales$sd)+senscales$mean)
mean((postm2xgreen$b_Intercept*greenscales$sd)+greenscales$mean)
sd((postm2xgreen$b_Intercept*greenscales$sd)+greenscales$mean)
  
postm2xgreen_eti<-ci(postm2xgreen, method = "ETI", ci = c(0.9, 0.95))
postm2xgreen_eti$CI_low<-(postm2xgreen_eti$CI_low*greenscales$sd)+greenscales$mean
postm2xgreen_eti$CI_high<-(postm2xgreen_eti$CI_high*greenscales$sd)+greenscales$mean

postm2xsen_eti<-ci(postm2xsen, method = "ETI", ci = c(0.9, 0.95))
postm2xsen_eti$CI_low<-(postm2xsen_eti$CI_low*senscales$sd)+senscales$mean
postm2xsen_eti$CI_high<-(postm2xsen_eti$CI_high*senscales$sd)+senscales$mean

#estimate flowering season length as days bw flower and flower end 
postm2xflow<- as_tibble(posterior_samples(fit_m2x_flow, pars = 
                                             c("b_Intercept")))
postm2xflowend<- as_tibble(posterior_samples(fit_m2x_flowend, pars = 
                                             c("b_Intercept")))

#calculate intercept vals for Table 3
mean((postm2xflowend$b_Intercept*flowendscales$sd)+flowendscales$mean)
sd((postm2xflowend$b_Intercept*flowendscales$sd)+flowendscales$mean)
mean((postm2xflow$b_Intercept*flowscales$sd)+flowscales$mean)
sd((postm2xflow$b_Intercept*flowscales$sd)+flowscales$mean)

postm2xflow_eti<-ci(postm2xflow, method = "ETI", ci = c(0.9, 0.95))
postm2xflow_eti$CI_low<-(postm2xflow_eti$CI_low*flowscales$sd)+flowscales$mean
postm2xflow_eti$CI_high<-(postm2xflow_eti$CI_high*flowscales$sd)+flowscales$mean

postm2xflowend_eti<-ci(postm2xflowend, method = "ETI", ci = c(0.9, 0.95))
postm2xflowend_eti$CI_low<-(postm2xflowend_eti$CI_low*flowendscales$sd)+flowendscales$mean
postm2xflowend_eti$CI_high<-(postm2xflowend_eti$CI_high*flowendscales$sd)+flowendscales$mean

#estimate fruiting season length as days bw fruiting and seed dispersal
postm2xfruit<- as_tibble(posterior_samples(fit_m2x_fruit, pars = 
                                             c("b_Intercept")))
postm2xdisp<- as_tibble(posterior_samples(fit_m2x_disp, pars = 
                                             c("b_Intercept")))
mean((postm2xfruit$b_Intercept*fruitscales$sd)+fruitscales$mean)
sd((postm2xfruit$b_Intercept*fruitscales$sd)+fruitscales$mean)
mean((postm2xdisp$b_Intercept*dispscales[1,2])+dispscales[1,1])
sd((postm2xdisp$b_Intercept*dispscales[1,2])+dispscales[1,1])

postm2xfruit_eti<-ci(postm2xfruit, method = "ETI", ci = c(0.9, 0.95))
postm2xfruit_eti$CI_low<-(postm2xfruit_eti$CI_low*fruitscales$sd)+fruitscales$mean
postm2xfruit_eti$CI_high<-(postm2xfruit_eti$CI_high*fruitscales$sd)+fruitscales$mean

postm2xdisp_eti<-ci(postm2xdisp, method = "ETI", ci = c(0.9, 0.95))
postm2xdisp_eti$CI_low<-(postm2xdisp_eti$CI_low*dispscales[1,2])+dispscales[1,1]
postm2xdisp_eti$CI_high<-(postm2xdisp_eti$CI_high*dispscales[1,2])+dispscales[1,1]
```

*Fig S1*

*Plot difference greenup to senescence 
```{r Growing season length, echo=FALSE,  warning=FALSE, error=FALSE, message=F}
etis<-ci(postgreensen, method = "ETI", ci = c(0.9, 0.95))
etis<-t(etis)
etis<-etis[c(3:4), ]%>%as.data.frame(.)

x<-ggplot(postgreensen, aes(x=diff))+geom_density(fill="#52854C")+theme_classic()+
  geom_vline(xintercept = 0, color="black")+ 
  geom_vline(xintercept=as.numeric(as.character(etis$V1)),color="red",lty=2,size=1)+
  geom_vline(xintercept=as.numeric(as.character(etis$V2)),color="grey",lty=2,size=1)+ 
  xlab(expression(Delta*"Days GSL in OTCs"))
x  

```


*Fig S2*

*Interaction between OTC and siteT for dispersal  

```{r plot interactions continuous , echo=FALSE, warning=FALSE, error=FALSE, message=F, results=FALSE,  fig.width=8, fig.height=6}
#set custom plotting theme-grobs on y axis  
transparent_theme <- theme( axis.title.y = element_blank(), axis.title.x = element_blank(),
                            axis.text.x = element_blank(), 
                            axis.text.y = element_blank(), 
                            axis.ticks.x = element_blank(), 
                            axis.ticks.y = element_blank(), 
                            panel.grid = element_blank(), 
                            axis.line = element_blank(), 
                            panel.background = element_blank(), 
                            plot.background = element_blank(), 
                            panel.border = element_blank(), 
                            panel.grid.major = element_blank(), 
                            panel.grid.minor = element_blank(), 
                            panel.grid.major.x = element_blank(),
                            panel.grid.major.y = element_blank())

#color pallette red and blue 
br=c("#800026","#BD0026","#E31A1C","#FC4E2A","#FD8D3C","#FEB24C", "#FED976","#FFEDA0","#FFFFCC",
     "#F7FBFF" ,"#DEEBF7" ,"#C6DBEF" ,"#9ECAE1" ,"#6BAED6" ,"#4292C6" ,"#2171B5" ,"#08519C" ,"#08306B")

#dispersal-siteT----
###Calculate OTC-CTL differences for all model replicates  
dat<-as_tibble(fit_m7x_disp$data)
xx<- unite(dat, all,spp, site_name, subsite, year, remove=F)%>%
  dplyr::select(site_name,spp, subsite, year, all, treatment, estimate, siteT)%>%
  group_by(all)%>%
  pivot_wider(names_from = treatment, values_from=estimate)%>%ungroup(.)%>%
  mutate(diff=(OTC-CTL))

#make plotting order for legend 
xxx<-mutate(xx, order=case_when(site_name=="BARROW"~1,  
site_name=="ALEXFIORD"~2, site_name=="ENDALEN"~3, 
site_name=="GAVIAPASS"~4, site_name=="LATNJA"~5, 
site_name=="ADVENTDALEN"~6, site_name=="ATQASUK"~7, 
site_name=="TOOLIK"~8, site_name=="DARING"~9))%>%
  mutate(site_name=case_when(site_name=="BARROW"~"UTQUIAVIK", TRUE~site_name))

#plot main plot with raw data 
#unscale siteT and diff estimates 
A <-ggplot(data=xxx, aes(x = (siteT*dispscales[2,2])+dispscales[2,1], y=diff*dispscales[1,2], 
                       color=reorder(site_name, order)))+
  geom_point(alpha=0.2, position="jitter")+
  geom_hline(yintercept = 0, lty=2)+labs(color="Site")+
  ylab(expression(Delta*"Days (OTC - CTL) "))+ ylim(-20, 17)+
  xlab("Avg temp dispersal period") +theme_classic() + xlim(3, 13) +
  scale_color_manual(values = 
  c(br[17],br[15], "#00b4ff", "#00e4ff", "#00ffa8","#ffe600", br[5], br[3], br[1]))+
  guides(color=guide_legend(override.aes = list(alpha=1)))

#add model predline 
#MAKE NEW DATA with OTC and CTL at 5 temps within actual ranges for site T, siteyr deltaT & stderr (values are mean centered)
#hist(fit_m7x_disp$data$siteT)
#summary(fit_m7x_disp)#siteT est error=0.09
nd <- tibble(
  siteT = c(-2, -1, 0, 1, 2,-2, -1, 0, 1, 2),
   std.error=c(0.1,0.1,0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1), 
   siteyear_deltaT= c(0, 0, 0, 0, 0,0, 0, 0, 0, 0),
treatment= c("OTC", "OTC", "OTC", "OTC", "OTC", "CTL", "CTL", "CTL", "CTL", "CTL"))

#use brms fitted function 
f <-
  fitted(fit_m7x_disp,
         newdata = nd,
         re_formula = NA,
         probs = c(.1, .9)) %>% 
  as_tibble() %>% 
  bind_cols(nd)

#calculate OTC-CTL fitted
f<-group_by(f, siteT)%>%pivot_wider(names_from = treatment, 
           values_from = c(Estimate, Est.Error, Q10, Q90))%>%
  mutate(diff=Estimate_OTC-Estimate_CTL,
         diff.err=Est.Error_OTC-Est.Error_CTL, 
         diff.Q10=Q10_OTC-Q10_CTL, 
         diff.Q90=Q90_OTC-Q90_CTL)

#plot predline 
f_plot<-
  ggplot(data=f, aes(x = (siteT*dispscales[2,2])+dispscales[2,1], y = diff*dispscales[1,2])) +
  geom_ribbon(aes(ymin = diff.Q10*dispscales[1,2], ymax = diff.Q90*dispscales[1,2]),
              fill = "grey", alpha=0.2) +
   xlim(3,13)+ geom_line()+
       theme(panel.background = element_blank())+
          ylim(-20, 17) + transparent_theme 


# Create the external graphical elements called a 'grop' in Grid terminology
p2_grob = ggplotGrob(f_plot)

# Insert p2_grob inside the ggplot
a<- A+ annotation_custom(grob = p2_grob)
a

```


*Fig S3*

*Interaction between OTC and leaf habit for greenup & senescence 

```{r leaf habit, echo=FALSE, warning=FALSE, error=FALSE, message=F, results=FALSE,  fig.width=8, fig.height=6}
#Greenup
#Intercepts 
postm8xgreen<- as_tibble(posterior_samples(fit_m8x_green, pars = 
                                             c("b_Intercept","b_leaf_habitevergreen")))
postm8xgreen$Decid<-postm8xgreen$b_Intercept
postm8xgreen$Ever<-postm8xgreen$b_Intercept + postm8xgreen$`b_leaf_habitevergreen` 

postm8xgreen<-dplyr::select(postm8xgreen,Decid, Ever)%>%
  pivot_longer(cols=c(Decid, Ever), names_to = "leafhabit", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
a<-ggplot(postm8xgreen, aes(x=(value*greenscales$sd)+greenscales$mean)) + 
  geom_density(aes(fill=leafhabit), alpha=0.8) + theme_classic()+
  xlab("DOY Green up ")+
  scale_fill_manual(values = c("#EDAE49","#66A182")) +# transparent_theme+
  #ggtitle(expression(Delta*"Days (OTC - CTL) Green up"))+xlim(-4, 3)+ylim(0,1)+
  theme(legend.position = "none")

#Slopes (OTC)
###Calculate pairwise differences between leaf habit types from model posteriors
postm8xgreen<- as_tibble(posterior_samples(fit_m8x_green, pars = 
                                           c("b_treatmentOTC","b_treatmentOTC:leaf_habitevergreen")))
postm8xgreen$Decid<-postm8xgreen$b_treatmentOTC
postm8xgreen$Ever<-postm8xgreen$Decid + postm8xgreen$`b_treatmentOTC:leaf_habitevergreen` 

postm8xgreen<-dplyr::select(postm8xgreen,Decid, Ever)%>%
  pivot_longer(cols=c(Decid, Ever), names_to = "leafhabit", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
b<-ggplot(postm8xgreen, aes(x=value*greenscales$sd)) + 
  geom_density(aes(fill=leafhabit), alpha=0.8) + theme_classic()+
  xlab("Days (OTC - CTL) Green up ")+
  scale_fill_manual(values = c("#EDAE49","#66A182")) +# transparent_theme+
  #ggtitle(expression(Delta*"Days (OTC - CTL) Green up"))+xlim(-4, 3)+ylim(0,1)+
  theme(legend.position = "none")

#Senescnece 
#Intercepts 
postm8xsen<- as_tibble(posterior_samples(fit_m8x_sen, pars = 
                                             c("b_Intercept","b_leaf_habitevergreen")))
postm8xsen$Decid<-postm8xsen$b_Intercept
postm8xsen$Ever<-postm8xsen$b_Intercept + postm8xsen$`b_leaf_habitevergreen` 

postm8xsen<-dplyr::select(postm8xsen,Decid, Ever)%>%
  pivot_longer(cols=c(Decid, Ever), names_to = "leafhabit", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
c<-ggplot(postm8xsen, aes(x=(value*senscales$sd)+senscales$mean)) + 
  geom_density(aes(fill=leafhabit), alpha=0.8) + theme_classic()+
  xlab("DOY Senescence ")+
  scale_fill_manual(values = c("#EDAE49","#66A182")) +# transparent_theme+
  #ggtitle(expression(Delta*"Days (OTC - CTL) Green up"))+xlim(-4, 3)+ylim(0,1)+
  theme(legend.position = "none")
#    plot.title = element_text(size = 10, hjust = 1, vjust=1.5))


#Slopes (OTC)
###Calculate pairwise differences between leaf habit types from model posteriors
postm8xsen<- as_tibble(posterior_samples(fit_m8x_sen, pars = 
                                             c("b_treatmentOTC","b_treatmentOTC:leaf_habitevergreen")))
postm8xsen$Decid<-postm8xsen$b_treatmentOTC
postm8xsen$Ever<-postm8xsen$Decid + postm8xsen$`b_treatmentOTC:leaf_habitevergreen` 

postm8xsen<-dplyr::select(postm8xsen,Decid, Ever)%>%
  pivot_longer(cols=c(Decid, Ever), names_to = "leafhabit", values_to = "value")

#Density plots for calculated pairwise differences w transparent background 
d<-ggplot(postm8xsen, aes(x=value*senscales$sd)) + 
  geom_density(aes(fill=leafhabit), alpha=0.8) + theme_classic()+
  xlab("Days (OTC - CTL) Senescence ")+
  scale_fill_manual(values = c("#EDAE49","#66A182")) +# transparent_theme+
  #ggtitle(expression(Delta*"Days (OTC - CTL) Green up"))+xlim(-4, 3)+ylim(0,1)+
  theme(
    legend.position = c(.95, .95),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6))

grid.arrange(a,b,c,d)

```


```{r interaction posteriors, echo=FALSE,  warning=FALSE, error=FALSE, message=F,  table.width=8, table.height=6}
#calculate posteriors and CIs for interactions-Table 3
#categorical 
#dispersal X OTC removal 
postm6xdisp<- as_tibble(posterior_samples(fit_m6x_disp, pars = 
  c("b_treatmentOTC","b_treatmentOTC:OTC_WinterRemovalY")))%>%mutate(scale=dispscales[1,2], phen="Disp")
postm6xdisp$Estimate<-mean(postm6xdisp$`b_treatmentOTC:OTCWinterRemovalY`)
postm6xdisp$Err<-sd(postm6xdisp$`b_treatmentOTC:OTCWinterRemovalY`)

postm6xdisp_eti<-ci(postm6xdisp, method = "ETI", ci = c(0.9, 0.95))%>%mutate(phen="Disp")%>%filter(Parameter=="b_treatmentOTC:OTCWinterRemovalY")
postm6xdisp<-dplyr::select(postm6xdisp, phen, scale, Estimate, Err)%>%distinct(.)
postdisp<-left_join(postm6xdisp, postm6xdisp_eti)

#combine and unscale for Table 3
postdispw<-pivot_wider(postdisp, names_from = "CI", values_from = c("CI_low", "CI_high"))%>%dplyr::select(Estimate, phen, Err, scale, Parameter, grep("CI", colnames(.)))%>%distinct(.)%>%mutate(Estimate=Estimate*scale, Err=Err*scale,CI_low_90=CI_low_90*scale, CI_high_90=CI_high_90*scale, CI_low_95=CI_low_95*scale, CI_high_95=CI_high_95*scale)%>%
  dplyr::select(Parameter, phen, Estimate, Err, CI_low_90, CI_high_90, CI_low_95, CI_high_95)

#flowering X soil moist 
postm5xflow<- as_tibble(posterior_samples(fit_m5x_flow, pars = 
c("b_treatmentOTC","b_treatmentOTC:commtypeMOIST")))%>%mutate(scale=flowscales$sd, phen="Flower")
postm5xflow$Estimate<-mean(postm5xflow$`b_treatmentOTC:commtypeMOIST`)
postm5xflow$Err<-sd(postm5xflow$`b_treatmentOTC:commtypeMOIST`)

postm5xflow_eti<-ci(postm5xflow, method = "ETI", ci = c(0.9, 0.95))%>%mutate(phen="Flower")%>%filter(Parameter=="b_treatmentOTC:commtypeMOIST")
postm5xflow<-dplyr::select(postm5xflow, phen, scale, Estimate, Err)%>%distinct(.)
postflow<-left_join(postm5xflow, postm5xflow_eti)

 #combine and unscale for Table 3
postflow<-pivot_wider(postflow, names_from = "CI", values_from = c("CI_low", "CI_high"))%>%dplyr::select(Estimate, phen, Err, scale, Parameter, grep("CI", colnames(.)))%>%distinct(.)%>%mutate(Estimate=Estimate*scale, Err=Err*scale, CI_low_90=CI_low_90*scale, CI_high_90=CI_high_90*scale, CI_low_95=CI_low_95*scale, CI_high_95=CI_high_95*scale)%>%
  dplyr::select(Parameter, phen, Estimate, Err, CI_low_90, CI_high_90, CI_low_95, CI_high_95)

#continuous 
#Dispersal x SiteT 
postm7xdisp<-as_tibble(posterior_samples(fit_m7x_disp, pars = 
  c("b_treatmentOTC:siteT")))%>%mutate(scale1=dispscales[1,2], scale2=dispscales[2,2], phen="Disp")%>%
  mutate(scale=scale1/scale2)#divide scales OTC/siteT

postm7xdisp$Estimate<-mean(postm7xdisp$`b_treatmentOTC:siteT`)
postm7xdisp$Err<-sd(postm7xdisp$`b_treatmentOTC:siteT`)

postm7xdisp_eti<-postm7xdisp_eti<-ci(postm7xdisp, method = "ETI", ci = c(0.9, 0.95))%>%mutate(phen="Disp")%>%filter(Parameter=="b_treatmentOTC:siteT")
postdisp2<-left_join(postm7xdisp, postm7xdisp_eti)
 
#combine and unscale for Table 3
postdisp2w<-pivot_wider(postdisp2, names_from = "CI", values_from = c("CI_low", "CI_high"))%>%dplyr::select(Estimate, Err, phen, scale, Parameter, grep("CI", colnames(.)))%>%distinct(.)%>%mutate(Estimate=Estimate*scale, Err=Err*scale,CI_low_90=CI_low_90*scale, CI_high_90=CI_high_90*scale, CI_low_95=CI_low_95*scale, CI_high_95=CI_high_95*scale)%>%
  dplyr::select(Parameter, phen, Estimate, Err, CI_low_90, CI_high_90, CI_low_95, CI_high_95)
 
table3<-rbind(etiw, postflow, postdispw, postdisp2w) 
kable(table3, caption="Table 3 Model estimates with bayestest eti intervals")
```

